### ISSUE TITLE
XML source is broken

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/linkset#51]
- stray '.' inside <section> text content
- dangling link target "item-links"

**Comment by hvdsomp** [comment]
Well, I'm just staring at this now. I did a local validation with the relax-ng schema and have two errors telling me that IDREFs `profile-parameter-example` and `Request_pr_par` have no matching IDs. Meaning there's targets without anchors. But the anchors are actually there:

- `<section title="Using a &quot;profile&quot; Parameter with a Link Set Media Type" anchor="profile-parameter-example">`
- `<figure title="Client HTTP HEAD request" anchor="Request_pr_par">`

As I said, I'm staring ...

**Comment by hvdsomp** [comment]
BTW, @dret, XML2RFC did eventually produce output, yesterday. But, somehow, as a result of this morning's edits [https://github.com/ietf-wg-httpapi/linkset/commit/6c218d387c5fa36bec72e544dece557f0105313c](https://github.com/ietf-wg-httpapi/linkset/commit/6c218d387c5fa36bec72e544dece557f0105313c) there are issues again.

**Comment by hvdsomp** [comment]
Fixed. [https://github.com/ietf-wg-httpapi/linkset/commit/92bd5c854bb01fa6965b944054119426fd28ff81](https://github.com/ietf-wg-httpapi/linkset/commit/92bd5c854bb01fa6965b944054119426fd28ff81)

**Comment by dret** [comment]
On 2021-10-05 17:40, Herbert Van de Sompel wrote:
> Fixed. 92bd5c8 

at least when i try it, xml2rfc still does not produce any output.

**Comment by reschke** [comment]
Online?

**Comment by reschke** [comment]
Apparently the online version wants 'version="3"' on the root element. Maybe to autodetect modes.

**Comment by hvdsomp** [comment]
You need to tick the choice “v3 text” in xml2rfc online. Works.

**Comment by dret** [comment]
On 2021-10-05 18:30, Julian Reschke wrote:
> Apparently the online version wants 'version="3"' on the root element. 
> Maybe to autodetect modes.

that was the only difference i could find against the version that 
worked, but then again we were told to remove it. putting it back in then.

**Comment by dret** [comment]
maybe this is ready to close then?

**Comment by reschke** [comment]
> worked, but then again we were told to remove it. putting it back in then.

Well, it had version==4 which did not make any sense :-)

**Comment by hvdsomp** [comment]
Closing because all fixed and figured out.
